# Site settings
title: Devfest Fsa 2019
description: Maior evento de desenvolvedores do interior da Bahia
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000"

# Configurações da Página
titulo: Devfest Fsa 2019
descricao: DEV Feira de Sanatana
user_title:

imagem: /assets/background.png
imagem_logo_principal: /assets/logo.png
imagem_logo: /assets/logoicone.png
imagem_logo_mobile: /assets/logoicone2.png
imagem_conteudo: /assets/background2.png

link_codconduta: https://github.com/gdgfsa/devfest2019/blob/master/CONDUTA.md
link_subpalestra: http://abre.ai/gdgfsapalestras
link_venda: https://www.sympla.com.br/gdg-devfest-fsa-2019__614974

contato_email: gdgfsaba@gmail.com
contato_instagram: https://www.instagram.com/gdgfsaba/?hl=pt
contato_facebook: https://www.facebook.com/gdgfsaba/

cor_padrao: rgb(92, 143, 245)

# Sobre o Evento
sobre: DevFests são eventos de comunidades de tecnologia que acontecem em várias partes do mundo estimulados pelo programa GDG da Google com palestras sobre várias áreas, atividades, workshops e muito mais. Teremos palestrantes de grande nome no cenário brasileiro, mas sem deixar de valorizar nossos talentos locais em um evento pautado na diversidade e inclusão. O GDG Feira de Santana se compromete a construir um evento inclusivo, diverso e seguro para que toda e qualquer pessoa interessada em tecnologia - de desenvolvedores iniciantes a profissionais experientes - possam participar desde que cumpra com todos os itens do nosso código de conduta.
where: FTC - Faculdade de Tecnologia e Ciências, Feira de Santana Avenida Artêmia Pires Freitas, 1390, Santo Antônio dos Prazeres Feira de Santana, BA
when: 30 de Novembro de 2019

# Patrocinadores
patrocinadores:
  - us:
    nome: Mandacaru Hackerspace
    imagem: assets/apoio/LogoVer.png
    link: https://www.instagram.com/mandacaruhs/
  - us:
    nome: Mandacaru Hackerspace
    imagem: assets/apoio/LogoVer.png
    link: https://www.instagram.com/mandacaruhs/
# Apoio

apoio:
  - us:
    nome: FTC
    imagem: assets/apoio/MARCA-FTC-SMALL.png
    link: https://www.ftc.br/feira-de-santana/home/
  - us:
    nome: Ecomp Jr.
    imagem: assets/apoio/ecompjr.png
    link: http://www.ecompjr.com.br/
  - us:
    nome: Mandacaru Hackerspace
    imagem: assets/apoio/LogoVer.png
    link: https://www.instagram.com/mandacaruhs/
  - us:
    nome: GDG Feira de Santana
    imagem: assets/apoio/GDG_Feira_de_santana.png
    link: https://www.instagram.com/gdgfsaba/?hl=pt
  - us:
    nome: GDG Lauro de Freitas
    imagem: assets/apoio/GDG__Lauro_de_Freitas.png
    link: https://pt-br.facebook.com/GdgLF/
  - us:
    nome: DevFSA
    imagem: assets/apoio/devfsa_logo.png
    link: https://devfsa.com.br/

# Palestrantes
palestrantes:
  - us:
    nome: Marcelo Bião
    imagem: assets/palestrantes/marcelo.png
    vinculo: Mandacaru Hackerspace
    texto: Sou Master das culinárias do Mandacaru Hackerspace. Faço um ótimo arroz com calabresa, mas esqueço na geladeira por uma semana. 
  - us:
    nome: Sérgio Matos
    imagem: assets/palestrantes/sergio.png
    vinculo: Mandacaru Hackerspace
    texto: Sou Master dos paranauês do Mandacaru Hackerspace. De vez em quando, eu esqueço de enviar a arte dos eventos.
  - us:
    nome: Vitor Cardim
    imagem: assets/palestrantes/vitor.png
    vinculo: Mandacaru Hackerspace
    texto: Sou Master of Cards do Mandacaru Hackerspace. Comi uma pizza de 3 queijos, fui procurar o banheiro e acabei parando em Uberlândia.
  - us:
    nome: Leo Melo
    imagem: assets/palestrantes/leonardo.png
    vinculo: Mandacaru Hackerspace
    texto: Sou Master arteiro do Mandacaru Hackerspace. Sou o maior nome representante do terraplanismo no globo. 
  - us:
    nome: Fábio Bispo
    imagem: assets/palestrantes/fabio.png
    vinculo: Mandacaru Hackerspace
    texto: Sou CEO do Mandacaru Hackerspace. Procuro meios de invadir a conta do telegram do Ministro da Justiça. Fogo nos racistas!

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
