# Site settings
title: Devfest Fsa 2019
description: Maior evento de desenvolvedores do interior da Bahia
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000"

# Configurações da Página
titulo: Devfest Fsa 2019
descricao: DEV Feira de Sanatana
user_title:

imagem: assets/background.png
imagem_logo: assets/logoicone.png
contato_email: leomachadoms@gmail.com
contato_instagram: google.com
contato_facebook: google.com

# Sobre o Evento
sobre: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam mi neque, fringilla vitae cursus nec, porta vitae eros. Aliquam facilisis molestie dui ac consequat. Duis et suscipit ipsum. Suspendisse potenti. Etiam suscipit ornare mi. Praesent porta posuere sapien eu aliquam. Curabitur vestibulum consequat nibh, at rhoncus turpis. Aliquam rhoncus metus in lorem suscipit congue. Phasellus non ante ipsum. Pellentesque vel diam dui. Donec dapibus mattis lorem, non ullamcorper arcu scelerisque nec. In euismod nulla a libero interdum sagittis. Vestibulum ultrices semper lacus, in tempor lorem maximus eu. Suspendisse posuere orci in ipsum congue, a elementum tortor semper. Vestibulum eget ipsum vel purus posuere placerat. Nam mattis eros a tincidunt bibendum. Pellentesque faucibus metus vitae dui varius bibendum. Etiam sed pellentesque felis. Aliquam a tortor ut sem fermentum pulvinar. Integer bibendum massa id tellus tempor consequat. Integer et mollis augue, id convallis lorem. Nam iaculis egestas diam nec iaculis. Curabitur a finibus tellus, at tempus lacus. Maecenas eget lectus sed enim ultricies rutrum nec at quam. Maecenas posuere volutpat facilisis. Integer sed consectetur mi.

# Patrocinadores
patrocinadores:
  - us:
    nome: Mandacaru Hackerspace
    imagem: assets/apoio/LogoVer.png
    link: http://www.google.com
  - us:
    nome: Mandacaru Hackerspace
    imagem: assets/apoio/LogoVer.png
    link: http://www.google.com
# Apoio

apoio:
  - us:
    nome: Mandacaru Hackerspace
    imagem: assets/apoio/LogoVer.png
    link:
  - us:
    nome: Mandacaru Hackerspace
    imagem: assets/apoio/LogoVer.png
    link:
  - us:
    nome: Mandacaru Hackerspace
    imagem: assets/apoio/LogoVer.png
    link:

# Palestrantes
palestrantes:
  - us:
    nome: Lorena Alguma-Coisa
    imagem: assets/palestrantes/lorena.jpg
    vinculo: Loucura
    texto: kjfhanejrhiu whbkjcfbwkjchnlkngkjh brjhabg fnjernqcfhnwrqngfufyegqnufgn ewaubnfuywrqbnfcukyenknryufcbnuebfcunyb g
  - us:
    nome: Lorena Alguma-Coisa
    imagem: assets/palestrantes/lorena.jpg
    vinculo: Loucura
    texto: Empresa foda aí
  - us:
    nome: Lorena Alguma-Coisa
    imagem: assets/palestrantes/lorena.jpg
    vinculo: Loucura
    texto: Empresa foda aí
  - us:
    nome: 2mj
    imagem: assets/palestrantes/ruanderson.jpg
    vinculo: Loucura
    texto: colé 2
  - us:
    nome: 3mj
    imagem: assets/palestrantes/marilia.jpg
    vinculo: Loucura
    texto: colé 2 
  - us:
    nome: 4mj
    imagem: assets/palestrantes/rodrigoalves.jpg
    vinculo: Loucura
    texto: colé 2 
  - us:
    nome: 5mj
    imagem: assets/favicon.ico
    vinculo: Loucura
    texto: colé 2
  - us:
    nome: 5mj
    imagem: assets/favicon.ico
    vinculo: Loucura
    texto: colé 2



# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
