# Site settings
title: Devfest Fsa 2019
description: Maior evento de desenvolvedores do interior da Bahia
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000"

# Configurações da Página
titulo: Devfest Fsa 2019
descricao: DEV Feira de Sanatana
user_title:

imagem: /assets/background.png
imagem_logo_principal: /assets/logo.png
imagem_logo: /assets/logoicone.png
imagem_logo_mobile: /assets/logoicone2.png
imagem_conteudo: /assets/background2.png

link_codconduta: https://github.com/gdgfsa/devfest2019/blob/master/CONDUTA.md
link_subpalestra: http://abre.ai/gdgfsapalestras
link_venda: https://www.sympla.com.br/gdg-devfest-fsa-2019__614974
link_patrocinio: http://abre.ai/gdgfsapatrocinio

contato_email: gdgfsaba@gmail.com
contato_instagram: https://www.instagram.com/gdgfsaba/?hl=pt
contato_facebook: https://www.facebook.com/gdgfsaba/

cor_padrao: rgb(92, 143, 245)

# Sobre o Evento
sobre: DevFests são eventos de comunidades de tecnologia que acontecem em várias partes do mundo estimulados pelo programa GDG da Google com palestras sobre várias áreas, atividades, workshops e muito mais. Teremos palestrantes de grande nome no cenário brasileiro, mas sem deixar de valorizar nossos talentos locais em um evento pautado na diversidade e inclusão. O GDG Feira de Santana se compromete a construir um evento inclusivo, diverso e seguro para que toda e qualquer pessoa interessada em tecnologia - de desenvolvedores iniciantes a profissionais experientes - possam participar desde que cumpra com todos os itens do nosso código de conduta.
where: FTC - Faculdade de Tecnologia e Ciências, Feira de Santana Avenida Artêmia Pires Freitas, 1390, Santo Antônio dos Prazeres Feira de Santana, BA
when: 30 de Novembro de 2019

# Patrocinadores
patrocinadores:
  - us:
    nome: Google Developers
    imagem: assets/patrocinio/google-developers-2.png
    link: https://developers.google.com/
  - us:
    nome: Ad Mobilize
    imagem: assets/patrocinio/admobilize-logo.svg
    link: https://www.admobilize.com/
    heigth: 350px
    width: 350px
  - us:
    nome: Skilo Pay
    imagem: assets/patrocinio/skilopay.png
    link: https://www.skilopay.com.br/
  - us:
    nome: Conexa
    imagem: assets/patrocinio/conexa.png
    link: https://conexa.app/
  
# Apoio

apoio:
  - us:
    nome: FTC
    imagem: assets/apoio/MARCA-FTC-SMALL.png
    link: https://www.ftc.br/feira-de-santana/home/
  - us:
    nome: Ecomp Jr.
    imagem: assets/apoio/ecompjr.png
    link: http://www.ecompjr.com.br/
  - us:
    nome: GDG Salvador
    imagem: assets/apoio/GDG_Salvador.png
    link: https://gdgssa.github.io/
  - us:
    nome: GDG Lauro de Freitas
    imagem: assets/apoio/GDG__Lauro_de_Freitas.png
    link: https://pt-br.facebook.com/GdgLF/
  - us:
    nome: ProgramAda
    imagem: assets/apoio/programadaPNG.png
    link: https://www.facebook.com/ProgramAdaOficial/
  - us:
    nome: DevFSA
    imagem: assets/apoio/devfsa_logo.png
    link: https://devfsa.com.br/
  - us:
    nome: Mandacaru Hackerspace
    imagem: assets/apoio/LogoVer.png
    link: https://www.instagram.com/mandacaruhs/
  - us:
    nome: Ben Melhor
    imagem: assets/apoio/bm2.png
    link: https://benmelhor.com.br/

# Palestrantes
palestrantes:
  - us:
    nome: Isabela Gonçalves
    imagem: assets/palestrantes/isabela_goncalves.jpg
    vinculo: Nubank
    texto: Baiana morando em SP sempre desejando por sol e praia, mas curtindo essa selva de pedra e o que ela tem pra oferecer. Crossfit girl que tenta codar um pouco, acredito e defendo muito que um bom desenvolvedor vai além de codar bem, envolve muito mais :)  Além disso, Netflix addicted.
  - us:
    nome: Elisabeth Mamede
    imagem: assets/palestrantes/isabela_mamede.jpg
    vinculo: Inmetrics
    texto: Uma QA formada em Sistemas de Informação, Pós graduanda em Engenharia de Software que ama café, chocolate, viagens e Muay Thai. Organizer do GDG Uberlândia e Women Techmakers Ambassador buscando incentivar cada vez mais mulheres e minorias no mundo da tecnologia!
  - us:
    nome: Sofia Marshallowitz
    imagem: assets/palestrantes/sofia_marshallowitz.jpeg
    vinculo: Lawgorithm e Legal Insight
    texto: Pesquisadora em Direito e I.A no Lawgorithm e Cientista de Dados na Legal Insight. Uma geek por dados procurando encrencas a serem resolvidas. Cientista de dados na Legal Insights e pesquisadora em Inteligência Artificial e Data Science no Lawgorithm. Estuda Statistics and Data Science pelo MITx, tem certificações na área de Ethical Hacking, achou uma falha aí no sistema da Caixa justamente na época de sacar o FGTS (https://thehack.com.br/site-da-caixa-esquece-autenticacao-e-facilita-consulta-de-fgts-e-pis-de-terceiros/ ) é estudante de Direito pela Universidade Mackenzie e em Análise e Desenvolvimento de Sistema na FATEC. Acredita que interdisciplinaridade é tudo e possivelmente é um bot."

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
