# Site settings
title: Devfest Fsa 2019
description: Maior evento de desenvolvedores do interior da Bahia
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000"

# Page settings
titulo: Devfest Fsa 2019
descricao: E aí... como tá?
user_title:

imagem: assets/background.png
imagem_logo: assets/logoicone.png
contato_email: leomachadoms@gmail.com
contato_instagram: google.com
contato_facebook: google.com

sobre: aqui está o primeiro campo e tals. Coloco aqui sobre o evento...

apoio:
  - us:
    nome: 1mj
    imagem: assets/favicon.ico
    texto: colé
  - us:
    nome: 2mj
    imagem: assets/favicon.ico
    texto: colé 2
  - us:
    nome: 3mj
    imagem: assets/favicon.ico
    texto: colé 2
  - us:
    nome: 4mj
    imagem: assets/favicon.ico
    texto: colé 2 
  - us:
    nome: 5mj
    imagem: assets/favicon.ico
    texto: colé 2 
  - us:
    nome: 6mj
    imagem: assets/favicon.ico
    texto: colé 2 

# Palestrantes
palestrantes:
  - us:
    nome: mmj
    imagem: assets/favicon.ico
    texto: colé
  - us:
    nome: 2mj
    imagem: assets/favicon.ico
    texto: colé 2
  - us:
    nome: 3mj
    imagem: assets/favicon.ico
    texto: colé 2 
  - us:
    nome: 4mj
    imagem: assets/favicon.ico
    texto: colé 2 
  - us:
    nome: 5mj
    imagem: assets/favicon.ico
    texto: colé 2 
  - us:
    nome: 6mj
    imagem: assets/favicon.ico
    texto: colé 2 
  - us:
    nome: 7mj
    imagem: assets/favicon.ico
    texto: colé 3



# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
